=== PanosEko/OilPriceX/xml/companyFuelOffers.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT company_fuel_offers (company_info, fuel_offers)>
<!ELEMENT company_info (name, tax_id, address)>
<!ELEMENT address (street, municipality, prefecture)>
<!ELEMENT fuel_offers (offer*)>
<!ELEMENT offer (fuel_type, end_date, price, active)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT tax_id (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT municipality (#PCDATA)>
<!ELEMENT prefecture (#PCDATA)>
<!ELEMENT fuel_type (#PCDATA)>
<!ELEMENT end_date (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT active (#PCDATA)>

=== PanosEko/OilPriceX/xml/companyFuelOffers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company_fuel_offers SYSTEM "../xml/companyFuelOffers.dtd">
<company_fuel_offers><company_info><name>Mesogeios Oil </name><tax_id>123123123</tax_id><address><street>Λεωφ. Μαραθώνος 89, Παλλήνη 153 51</street><municipality>Αβδήρων</municipality><prefecture>Αττικής</prefecture></address></company_info><fuel_offers><offer><fuel_type>Βενζίνη 95</fuel_type><end_date>2024-12-13</end_date><price>1.68</price><active>True</active></offer><offer><fuel_type>Βενζίνη 95</fuel_type><end_date>2023-01-01</end_date><price>1.62</price><active>False</active></offer><offer><fuel_type>Βενζίνη 95</fuel_type><end_date>2023-01-01</end_date><price>1.62</price><active>False</active></offer><offer><fuel_type>Βενζίνη 95</fuel_type><end_date>2022-01-01</end_date><price>2.14</price><active>False</active></offer><offer><fuel_type>Βενζίνη 98</fuel_type><end_date>2024-01-01</end_date><price>1.89</price><active>True</active></offer><offer><fuel_type>Βενζίνη 98</fuel_type><end_date>2023-01-01</end_date><price>1.82</price><active>False</active></offer><offer><fuel_type>Βενζίνη 98</fuel_type><end_date>2023-01-01</end_date><price>1.56</price><active>False</active></offer><offer><fuel_type>Βενζίνη 98</fuel_type><end_date>2022-01-01</end_date><price>2.03</price><active>False</active></offer><offer><fuel_type>Πετρέλαιο Κίνησης</fuel_type><end_date>2024-01-01</end_date><price>1.39</price><active>True</active></offer><offer><fuel_type>Πετρέλαιο Κίνησης</fuel_type><end_date>2023-01-01</end_date><price>1.32</price><active>False</active></offer><offer><fuel_type>Πετρέλαιο Κίνησης</fuel_type><end_date>2022-01-01</end_date><price>1.67</price><active>False</active></offer><offer><fuel_type>Πετρέλαιο Θέρμανσης</fuel_type><end_date>2024-01-01</end_date><price>1.19</price><active>True</active></offer><offer><fuel_type>Πετρέλαιο Θέρμανσης</fuel_type><end_date>2023-01-01</end_date><price>1.12</price><active>False</active></offer><offer><fuel_type>Πετρέλαιο Θέρμανσης</fuel_type><end_date>2022-01-01</end_date><price>1.56</price><active>False</active></offer></fuel_offers></company_fuel_offers>
